/* ============================================================
   QOIX Synthesizer — Sound Design Presets
   ============================================================ */

'use strict';

const Presets = [
  {
    name: 'Init',
    osc1:   { enabled: true,  wave: 'sawtooth', octave: 0,  detune: 0,  level: 0.8 },
    osc2:   { enabled: false, wave: 'square',   octave: 0,  detune: 7,  level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.2 },
    env:    { attack: 0.01, decay: 0.1,  sustain: 0.7,  release: 0.3 },
    fenv:   { amount: 2000,  attack: 0.01, decay: 0.2,  sustain: 0.3,  release: 0.2 },
    filter: { type: 'lowpass', cutoff: 8000, resonance: 1 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.3, target: 'pitch' },
    dist:   { enabled: false, drive: 80 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.5 },
    delay:  { enabled: false, time: 0.375, feedback: 0.4, mix: 0.3 },
    reverb: { enabled: false, size: 2, damp: 0.5, mix: 0.2 },
  },

  {
    name: 'Lead — Screaming Saw',
    osc1:   { enabled: true,  wave: 'sawtooth', octave: 0,  detune: -5, level: 0.9 },
    osc2:   { enabled: true,  wave: 'sawtooth', octave: 0,  detune: 5,  level: 0.7 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.005, decay: 0.08, sustain: 0.9, release: 0.15 },
    fenv:   { amount: 5000,  attack: 0.005, decay: 0.15, sustain: 0.2,  release: 0.1 },
    filter: { type: 'lowpass', cutoff: 3000, resonance: 8 },
    lfo:    { enabled: true,  wave: 'sine', rate: 5.5, depth: 0.15, target: 'pitch' },
    dist:   { enabled: true,  drive: 60 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.5 },
    delay:  { enabled: true,  time: 0.25, feedback: 0.3, mix: 0.25 },
    reverb: { enabled: true,  size: 1.5, damp: 0.6, mix: 0.15 },
  },

  {
    name: 'Bass — Deep Sub',
    osc1:   { enabled: true,  wave: 'sine',     octave: -1, detune: 0,  level: 1.0 },
    osc2:   { enabled: true,  wave: 'square',   octave: -2, detune: 0,  level: 0.4 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.003, decay: 0.3,  sustain: 0.6,  release: 0.25 },
    fenv:   { amount: 1500,  attack: 0.003, decay: 0.25, sustain: 0.0,  release: 0.2 },
    filter: { type: 'lowpass', cutoff: 400, resonance: 2 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: false, drive: 40 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.375, feedback: 0.3, mix: 0.2 },
    reverb: { enabled: false, size: 1, damp: 0.8, mix: 0.05 },
  },

  {
    name: 'Bass — Growling 303',
    osc1:   { enabled: true,  wave: 'sawtooth', octave: -1, detune: 0,  level: 0.9 },
    osc2:   { enabled: false, wave: 'square',   octave: -1, detune: 0,  level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.003, decay: 0.12, sustain: 0.5,  release: 0.1 },
    fenv:   { amount: 7000,  attack: 0.003, decay: 0.2,  sustain: 0.0,  release: 0.1 },
    filter: { type: 'lowpass', cutoff: 350, resonance: 18 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: true,  drive: 30 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.375, feedback: 0.3, mix: 0.2 },
    reverb: { enabled: false, size: 1, damp: 0.8, mix: 0.05 },
  },

  {
    name: 'Pad — Warm Strings',
    osc1:   { enabled: true,  wave: 'sawtooth', octave: 0,  detune: -8, level: 0.7 },
    osc2:   { enabled: true,  wave: 'sawtooth', octave: 1,  detune: 8,  level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.05 },
    env:    { attack: 0.6,   decay: 0.5,  sustain: 0.8,  release: 1.2 },
    fenv:   { amount: 1000,  attack: 0.6,  decay: 0.8,  sustain: 0.4,  release: 0.8 },
    filter: { type: 'lowpass', cutoff: 2000, resonance: 1.5 },
    lfo:    { enabled: true,  wave: 'sine', rate: 3.5, depth: 0.1, target: 'pitch' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: true,  rate: 0.8, depth: 0.006, mix: 0.6 },
    delay:  { enabled: true,  time: 0.45, feedback: 0.35, mix: 0.2 },
    reverb: { enabled: true,  size: 4, damp: 0.4, mix: 0.4 },
  },

  {
    name: 'Pad — Dark Atmospheric',
    osc1:   { enabled: true,  wave: 'triangle', octave: 0,  detune: -12, level: 0.8 },
    osc2:   { enabled: true,  wave: 'sine',     octave: 1,  detune: 12,  level: 0.6 },
    noise:  { enabled: true,  type: 'pink', level: 0.08 },
    env:    { attack: 1.2,   decay: 1.0,  sustain: 0.7,  release: 2.5 },
    fenv:   { amount: 500,   attack: 1.5,  decay: 2.0,  sustain: 0.3,  release: 2.0 },
    filter: { type: 'lowpass', cutoff: 900, resonance: 3 },
    lfo:    { enabled: true,  wave: 'sine', rate: 0.3, depth: 0.2, target: 'filter' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: true,  rate: 0.4, depth: 0.008, mix: 0.7 },
    delay:  { enabled: true,  time: 0.6, feedback: 0.5, mix: 0.4 },
    reverb: { enabled: true,  size: 5, damp: 0.3, mix: 0.55 },
  },

  {
    name: 'Pluck — Crystal Keys',
    osc1:   { enabled: true,  wave: 'triangle', octave: 0,  detune: 0,  level: 0.9 },
    osc2:   { enabled: true,  wave: 'sine',     octave: 1,  detune: 0,  level: 0.4 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.001, decay: 0.35, sustain: 0.0,  release: 0.4 },
    fenv:   { amount: 6000,  attack: 0.001, decay: 0.3,  sustain: 0.0,  release: 0.3 },
    filter: { type: 'lowpass', cutoff: 1200, resonance: 4 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: true,  time: 0.3, feedback: 0.4, mix: 0.3 },
    reverb: { enabled: true,  size: 2.5, damp: 0.6, mix: 0.3 },
  },

  {
    name: 'Pluck — Metallic Bell',
    osc1:   { enabled: true,  wave: 'sine',     octave: 0,  detune: 0,  level: 0.8 },
    osc2:   { enabled: true,  wave: 'sine',     octave: 2,  detune: 14, level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.001, decay: 0.8,  sustain: 0.0,  release: 1.2 },
    fenv:   { amount: 3000,  attack: 0.001, decay: 0.5,  sustain: 0.0,  release: 0.8 },
    filter: { type: 'bandpass', cutoff: 3000, resonance: 6 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: true,  time: 0.5, feedback: 0.45, mix: 0.35 },
    reverb: { enabled: true,  size: 3, damp: 0.5, mix: 0.35 },
  },

  {
    name: 'Keys — Electric Piano',
    osc1:   { enabled: true,  wave: 'triangle', octave: 0,  detune: 0,  level: 0.85 },
    osc2:   { enabled: true,  wave: 'sine',     octave: 0,  detune: 2,  level: 0.3 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.003, decay: 0.5,  sustain: 0.3,  release: 0.5 },
    fenv:   { amount: 3000,  attack: 0.003, decay: 0.4,  sustain: 0.0,  release: 0.4 },
    filter: { type: 'lowpass', cutoff: 4000, resonance: 2 },
    lfo:    { enabled: true,  wave: 'sine', rate: 3.8, depth: 0.12, target: 'amplitude' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: true,  rate: 1.2, depth: 0.004, mix: 0.4 },
    delay:  { enabled: false, time: 0.3, feedback: 0.3, mix: 0.2 },
    reverb: { enabled: true,  size: 1.5, damp: 0.7, mix: 0.2 },
  },

  {
    name: 'Keys — Honky Organ',
    osc1:   { enabled: true,  wave: 'square',   octave: 0,  detune: 0,  level: 0.7 },
    osc2:   { enabled: true,  wave: 'square',   octave: 1,  detune: 3,  level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.005, decay: 0.01, sustain: 1.0,  release: 0.05 },
    fenv:   { amount: 0,     attack: 0.01, decay: 0.1,  sustain: 1.0,  release: 0.05 },
    filter: { type: 'lowpass', cutoff: 6000, resonance: 1 },
    lfo:    { enabled: true,  wave: 'sine', rate: 6, depth: 0.1, target: 'amplitude' },
    dist:   { enabled: true,  drive: 50 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.375, feedback: 0.3, mix: 0.2 },
    reverb: { enabled: true,  size: 1, damp: 0.8, mix: 0.1 },
  },

  {
    name: 'Arp — Staccato Pulse',
    osc1:   { enabled: true,  wave: 'square',   octave: 0,  detune: 0,  level: 0.8 },
    osc2:   { enabled: false, wave: 'square',   octave: 0,  detune: 0,  level: 0.5 },
    noise:  { enabled: false, type: 'white', level: 0.0 },
    env:    { attack: 0.003, decay: 0.12, sustain: 0.0,  release: 0.08 },
    fenv:   { amount: 4000,  attack: 0.003, decay: 0.12, sustain: 0.0,  release: 0.08 },
    filter: { type: 'lowpass', cutoff: 1500, resonance: 10 },
    lfo:    { enabled: false, wave: 'sine', rate: 8, depth: 0.2, target: 'pitch' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: true,  time: 0.188, feedback: 0.5, mix: 0.4 },
    reverb: { enabled: true,  size: 2, damp: 0.5, mix: 0.2 },
  },

  {
    name: 'FX — Wind Sweep',
    osc1:   { enabled: false, wave: 'sawtooth', octave: 0,  detune: 0,  level: 0.5 },
    osc2:   { enabled: false, wave: 'sawtooth', octave: 0,  detune: 0,  level: 0.5 },
    noise:  { enabled: true,  type: 'pink', level: 0.5 },
    env:    { attack: 1.5,   decay: 1.0,  sustain: 0.6,  release: 2.0 },
    fenv:   { amount: 8000,  attack: 2.0,  decay: 3.0,  sustain: 0.1,  release: 2.0 },
    filter: { type: 'bandpass', cutoff: 600, resonance: 8 },
    lfo:    { enabled: true,  wave: 'sine', rate: 0.2, depth: 0.4, target: 'filter' },
    dist:   { enabled: false, drive: 20 },
    chorus: { enabled: false, rate: 0.5, depth: 0.005, mix: 0.5 },
    delay:  { enabled: true,  time: 0.7, feedback: 0.6, mix: 0.4 },
    reverb: { enabled: true,  size: 5.5, damp: 0.2, mix: 0.7 },
  },

  {
    name: 'FX — Laser Zap',
    osc1:   { enabled: true,  wave: 'sawtooth', octave: 1,  detune: 0,  level: 0.9 },
    osc2:   { enabled: false, wave: 'sine',     octave: 1,  detune: 0,  level: 0.4 },
    noise:  { enabled: true,  type: 'white', level: 0.1 },
    env:    { attack: 0.001, decay: 0.08, sustain: 0.0,  release: 0.05 },
    fenv:   { amount: -12000, attack: 0.001, decay: 0.08, sustain: 0.0, release: 0.05 },
    filter: { type: 'highpass', cutoff: 800, resonance: 5 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: true,  drive: 150 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.1, feedback: 0.2, mix: 0.15 },
    reverb: { enabled: true,  size: 0.5, damp: 0.9, mix: 0.1 },
  },

  {
    name: 'Drum — Kick',
    osc1:   { enabled: true,  wave: 'sine',     octave: -2, detune: 0,  level: 1.0 },
    osc2:   { enabled: false, wave: 'sine',     octave: -2, detune: 0,  level: 0.5 },
    noise:  { enabled: true,  type: 'white', level: 0.15 },
    env:    { attack: 0.001, decay: 0.25, sustain: 0.0,  release: 0.15 },
    fenv:   { amount: -5000, attack: 0.001, decay: 0.08, sustain: 0.0,  release: 0.05 },
    filter: { type: 'lowpass', cutoff: 200, resonance: 1 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: true,  drive: 100 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.375, feedback: 0.2, mix: 0.1 },
    reverb: { enabled: false, size: 0.3, damp: 0.9, mix: 0.05 },
  },

  {
    name: 'Drum — Snare',
    osc1:   { enabled: true,  wave: 'triangle', octave: -1, detune: 0,  level: 0.6 },
    osc2:   { enabled: false, wave: 'sine',     octave: -1, detune: 0,  level: 0.4 },
    noise:  { enabled: true,  type: 'white', level: 0.55 },
    env:    { attack: 0.001, decay: 0.12, sustain: 0.0,  release: 0.1 },
    fenv:   { amount: 2000,  attack: 0.001, decay: 0.1,  sustain: 0.0,  release: 0.08 },
    filter: { type: 'highpass', cutoff: 1500, resonance: 3 },
    lfo:    { enabled: false, wave: 'sine', rate: 4, depth: 0.1, target: 'pitch' },
    dist:   { enabled: true,  drive: 80 },
    chorus: { enabled: false, rate: 1.5, depth: 0.003, mix: 0.3 },
    delay:  { enabled: false, time: 0.2, feedback: 0.2, mix: 0.1 },
    reverb: { enabled: true,  size: 0.8, damp: 0.7, mix: 0.15 },
  },
];
